// Generated by CoffeeScript 1.4.0
(function() {
  var factory, jQuery, _ref,
    __hasProp = {}.hasOwnProperty;

  factory = function($) {
    var Step;
    Step = (function() {

      Step.prototype.header = '';

      Step.prototype.content = '';

      Step.prototype.buttons = null;

      Step.prototype.defaultButton = 'Continue';

      Step.prototype.attachment = null;

      Step.prototype.className = '';

      Step.prototype.nextOn = null;

      Step.prototype.block = '';

      Step.prototype.focus = '';

      Step.prototype.onEnter = null;

      Step.prototype.onExit = null;

      Step.prototype.blockers = null;

      Step.prototype.focusers = null;

      function Step(params) {
        var button, property, value, _base;
        if (params == null) {
          params = {};
        }
        for (property in params) {
          if (!__hasProp.call(params, property)) continue;
          value = params[property];
          if (property in this) {
            this[property] = value;
          }
        }
        if ((!this.buttons) && (!this.nextOn)) {
          button = {};
          button[this.defaultButton] = 'ZOOTORIAL_NEXT';
          this.buttons = [button];
          this.nextOn = {
            click: 'button[value="ZOOTORIAL_NEXT"]'
          };
        }
        this.buttons || (this.buttons = []);
        this.attachment || (this.attachment = {
          to: null
        });
        (_base = this.attachment).at || (_base.at = {});
        this.nextOn || (this.nextOn = {
          click: '.tutorial.zootorial-dialog'
        });
      }

      Step.prototype.createBlockers = function() {
        var blocked, blocker, _i, _len, _ref, _results;
        this.blockers = $();
        _ref = $(this.block);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          blocked = _ref[_i];
          blocked = $(blocked);
          blocker = $('<div class="hidden zootorial-blocker"></div>');
          blocker.width(blocked.outerWidth());
          blocker.height(blocked.outerHeight());
          blocker.offset(blocked.offset());
          _results.push(this.blockers = this.blockers.add(blocker));
        }
        return _results;
      };

      Step.prototype.createFocusers = function() {
        var above, bottom, focus, height, left, offset, right, totalHeight, totalWidth, width;
        this.focusers = $((new Array(4 + 1)).join('<div class="hidden zootorial-focuser"></div>'));
        focus = $(this.focus).filter(':visible').first();
        if (focus.length === 0) {
          return;
        }
        offset = focus.offset();
        width = focus.outerWidth();
        height = focus.outerHeight();
        totalHeight = $('html').outerHeight();
        totalWidth = $('html').outerWidth();
        above = this.focusers.eq(0);
        above.offset({
          left: 0,
          top: 0
        });
        above.width('100%');
        above.height(offset.top);
        right = this.focusers.eq(1);
        right.offset({
          left: offset.left + width,
          top: offset.top
        });
        right.width(totalWidth - offset.left - width);
        right.height(height);
        bottom = this.focusers.eq(2);
        bottom.offset({
          left: 0,
          top: offset.top + height
        });
        bottom.width('100%');
        bottom.height(totalHeight - offset.top - height);
        left = this.focusers.eq(3);
        left.offset({
          left: 0,
          top: offset.top
        });
        left.width(offset.left);
        return left.height(height);
      };

      Step.prototype.enter = function(tutorial) {
        var eventName, extras, selector, _ref;
        tutorial.dialog.el.trigger('enter-tutorial-step', [tutorial.step, this]);
        if (typeof this.onEnter === "function") {
          this.onEnter(tutorial, this);
        }
        tutorial.dialog.attachment = this.attachment;
        tutorial.dialog.header = this.header;
        tutorial.dialog.content = this.content;
        tutorial.dialog.buttons = this.buttons;
        tutorial.dialog.render();
        if (this.className) {
          tutorial.dialog.el.addClass(this.className);
        }
        _ref = this.nextOn;
        for (eventName in _ref) {
          selector = _ref[eventName];
          $(document).on(eventName, selector, tutorial.next);
        }
        this.createBlockers();
        this.createFocusers();
        extras = this.blockers.add(this.focusers);
        extras.appendTo('body');
        extras.css({
          position: ''
        });
        return setTimeout($.proxy($.prototype.removeClass, extras, 'hidden'), tutorial.dialog.attachmentDelay);
      };

      Step.prototype.exit = function(tutorial) {
        var eventName, extras, selector, _ref;
        tutorial.dialog.el.trigger('exit-tutorial-step', [tutorial.step, this]);
        if (typeof this.onExit === "function") {
          this.onExit(tutorial, this);
        }
        if (this.className) {
          tutorial.dialog.el.removeClass(this.className);
        }
        _ref = this.nextOn;
        for (eventName in _ref) {
          selector = _ref[eventName];
          $(document).off(eventName, selector, tutorial.next);
        }
        extras = this.blockers.add(this.focusers);
        extras.addClass('hidden');
        return setTimeout($.proxy($.prototype.remove, extras), tutorial.dialog.attachmentDelay);
      };

      return Step;

    })();
    return Step;
  };

  if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['jquery'], factory);
  } else {
    jQuery = window.jQuery;
    if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
      module.exports = factory(jQuery);
    } else {
      if ((_ref = window.zootorial) == null) {
        window.zootorial = {};
      }
      window.zootorial.Step = factory(jQuery);
    }
  }

}).call(this);
