// Generated by CoffeeScript 1.4.0
(function() {
  var Dialog, Step, factory, jQuery, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty;

  factory = function($, Step, Dialog) {
    var Tutorial;
    Tutorial = (function() {

      Tutorial.Step = Step;

      Tutorial.prototype.steps = null;

      Tutorial.prototype.step = -1;

      function Tutorial(params) {
        var property, value;
        if (params == null) {
          params = {};
        }
        for (property in params) {
          if (!__hasProp.call(params, property)) continue;
          value = params[property];
          if (property in this) {
            this[property] = value;
          }
        }
        this.dialog = new Dialog(params);
        this.dialog.el.addClass('tutorial');
      }

      Tutorial.prototype.start = function() {
        this.goTo(0);
        this.dialog.open();
        return this.dialog.el.trigger('start-tutorial');
      };

      Tutorial.prototype.next = function() {
        return this.goTo(this.step + 1);
      };

      Tutorial.prototype.goTo = function(step) {
        var _ref;
        if ((_ref = this.steps[this.step]) != null) {
          _ref.exit(this);
        }
        this.step = step;
        if (this.steps[this.step]) {
          return this.steps[this.step].enter(this);
        } else {
          return this.end();
        }
      };

      Tutorial.prototype.end = function() {
        var _ref;
        if ((_ref = this.steps[this.step]) != null) {
          _ref.exit(this);
        }
        this.dialog.close();
        this.step = -1;
        return this.dialog.el.trigger('end-tutorial');
      };

      return Tutorial;

    })();
    return Tutorial;
  };

  if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['jquery', './step', './dialog'], factory);
  } else {
    jQuery = window.jQuery;
    Step = (_ref = window.zootorial) != null ? _ref.Step : void 0;
    Dialog = (_ref1 = window.zootorial) != null ? _ref1.Dialog : void 0;
    if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
      if (Step == null) {
        Step = require('./step');
      }
      if (Dialog == null) {
        Dialog = require('./dialog');
      }
      module.exports = factory(jQuery, Dialog);
    } else {
      if ((_ref2 = window.zootorial) == null) {
        window.zootorial = {};
      }
      window.zootorial.Tutorial = factory(jQuery, Step, Dialog);
    }
  }

}).call(this);
