// Generated by CoffeeScript 1.4.0
(function() {
  var Dialog, Step, Tutorial, attach, factory, _ref, _ref1, _ref2, _ref3;

  factory = function(attach, Dialog, Step, Tutorial) {
    return {
      attach: attach,
      Dialog: Dialog,
      Step: Step,
      Tutorial: Tutorial
    };
  };

  if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['./attach', './dialog', './step', './tutorial'], factory);
  } else {
    attach = (_ref = window.zootorial) != null ? _ref.attach : void 0;
    Dialog = (_ref1 = window.zootorial) != null ? _ref1.Dialog : void 0;
    Step = (_ref2 = window.zootorial) != null ? _ref2.Step : void 0;
    Tutorial = (_ref3 = window.zootorial) != null ? _ref3.Tutorial : void 0;
    if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
      if (attach == null) {
        attach = require('./attach');
      }
      if (Dialog == null) {
        Dialog = require('./dialog');
      }
      if (Step == null) {
        Step = require('./step');
      }
      if (Tutorial == null) {
        Tutorial = require('./tutorial');
      }
      module.exports = factory(attach, Dialog, Step, Tutorial);
    }
  }

}).call(this);
