// Generated by CoffeeScript 1.4.0
(function() {
  var Dialog, Tutorial, attach, factory, _ref, _ref1, _ref2, _ref3;

  factory = function(attach, Dialog, Tutorial) {
    return {
      attach: attach,
      Dialog: Dialog,
      Tutorial: Tutorial
    };
  };

  if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(['./attach', './dialog', './tutorial'], factory);
  } else {
    attach = (_ref = window.zootorial) != null ? _ref.attach : void 0;
    Dialog = (_ref1 = window.zootorial) != null ? _ref1.Dialog : void 0;
    Tutorial = (_ref2 = window.zootorial) != null ? _ref2.Tutorial : void 0;
    if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
      if (attach == null) {
        attach = require('./attach');
      }
      if (Dialog == null) {
        Dialog = require('./dialog');
      }
      if (Tutorial == null) {
        Tutorial = require('./tutorial');
      }
      module.exports = factory(attach, Dialog, Tutorial);
    } else {
      if ((_ref3 = window.zootorial) == null) {
        window.zootorial = {};
      }
      window.zootorial = factory(attach, Dialog, Tutorial);
    }
  }

}).call(this);
